[kali_vms]
192.168.3.10 ansible_user=redteam ansible_password=redteam ansible_become_password=redteam
192.168.3.12 ansible_user=redteam ansible_password=redteam ansible_become_password=redteam
192.168.3.14 ansible_user=redteam ansible_password=redteam ansible_become_password=redteam
192.168.3.16 ansible_user=redteam ansible_password=redteam ansible_become_password=redteam
192.168.3.18 ansible_user=redteam ansible_password=redteam ansible_become_password=redteam
192.168.3.20 ansible_user=redteam ansible_password=redteam ansible_become_password=redteam
192.168.3.22 ansible_user=redteam ansible_password=redteam ansible_become_password=redteam
192.168.3.24 ansible_user=redteam ansible_password=redteam ansible_become_password=redteam
192.168.3.26 ansible_user=redteam ansible_password=redteam ansible_become_password=redteam
192.168.3.28 ansible_user=redteam ansible_password=redteam ansible_become_password=redteam

[kali_vms:vars]
ansible_ssh_common_args='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
ansible_python_interpreter=/usr/bin/python3
