---
- name: CCDC Windows Hardening Playbook
  hosts: all
  gather_facts: yes
  connection: local
  tasks:

    # Task 1: Delete SSH service
    - name: Check if OpenSSH Server service exists
      win_service:
        name: sshd
      register: ssh_service
      ignore_errors: yes

    - name: Stop and disable OpenSSH Server
      win_service:
        name: sshd
        state: stopped
        start_mode: disabled
      when: ssh_service is succeeded
      ignore_errors: yes

    - name: Remove OpenSSH Server feature
      win_optional_feature:
        name: OpenSSH.Server~~~~0.0.1.0
        state: absent
      ignore_errors: yes

    # Task 2: Restrict RDP access to approved users only
    - name: Get current members of Remote Desktop Users group
      win_shell: |
        $members = Get-LocalGroupMember -Group "Remote Desktop Users" -ErrorAction SilentlyContinue
        $members | ForEach-Object { $_.Name }
      register: rdp_users
      ignore_errors: yes

    - name: Remove unauthorized users from Remote Desktop Users group
      win_shell: |
        $allowedUsers = @('blueteam', 'greyteam', 'greyteam2')
        $members = Get-LocalGroupMember -Group "Remote Desktop Users" -ErrorAction SilentlyContinue
        
        foreach ($member in $members) {
          $username = $member.Name.Split('\')[-1]
          if ($username -notin $allowedUsers) {
            Remove-LocalGroupMember -Group "Remote Desktop Users" -Member $member.Name -ErrorAction SilentlyContinue
            Write-Output "Removed: $($member.Name)"
          }
        }
      ignore_errors: yes

    - name: Ensure approved users are in Remote Desktop Users group
      win_group_membership:
        name: Remote Desktop Users
        members:
          - blueteam
          - greyteam
          - greyteam2
        state: present
      ignore_errors: yes

    # Task 3: Download Sysinternals tools
    - name: Create Sysinternals directory
      win_file:
        path: C:\Sysinternals
        state: directory

    - name: Download AD Explorer
      win_get_url:
        url: https://live.sysinternals.com/ADExplorer.exe
        dest: C:\Sysinternals\ADExplorer.exe
      ignore_errors: yes

    - name: Download Process Explorer
      win_get_url:
        url: https://live.sysinternals.com/procexp.exe
        dest: C:\Sysinternals\procexp.exe
      ignore_errors: yes

    - name: Download LogonSessions
      win_get_url:
        url: https://live.sysinternals.com/logonsessions.exe
        dest: C:\Sysinternals\logonsessions.exe
      ignore_errors: yes

    - name: Download Autoruns
      win_get_url:
        url: https://live.sysinternals.com/autoruns.exe
        dest: C:\Sysinternals\autoruns.exe
      ignore_errors: yes

    - name: Download Sysmon
      win_get_url:
        url: https://live.sysinternals.com/Sysmon.exe
        dest: C:\Sysinternals\Sysmon.exe
      ignore_errors: yes

    - name: Download Sysmon64
      win_get_url:
        url: https://live.sysinternals.com/Sysmon64.exe
        dest: C:\Sysinternals\Sysmon64.exe
      register: sysmon_download
      ignore_errors: yes

    - name: Download SwiftOnSecurity Sysmon config
      win_get_url:
        url: https://raw.githubusercontent.com/SwiftOnSecurity/sysmon-config/master/sysmonconfig-export.xml
        dest: C:\Sysinternals\sysmon-config.xml
      register: sysmon_config_download
      ignore_errors: yes

    - name: Check if Sysmon executable exists
      win_stat:
        path: C:\Sysinternals\Sysmon64.exe
      register: sysmon_exe_file

    - name: Check if Sysmon config was downloaded
      win_stat:
        path: C:\Sysinternals\sysmon-config.xml
      register: sysmon_config_file

    - name: Uninstall existing Sysmon (if present)
      win_shell: |
        C:\Sysinternals\Sysmon64.exe -u force
      when: sysmon_exe_file.stat.exists and sysmon_config_file.stat.exists
      ignore_errors: yes

    - name: Install Sysmon with SwiftOnSecurity config
      win_shell: |
        C:\Sysinternals\Sysmon64.exe -accepteula -i C:\Sysinternals\sysmon-config.xml
      when: sysmon_exe_file.stat.exists and sysmon_config_file.stat.exists
      register: sysmon_install
      ignore_errors: yes

    - name: Wait for Sysmon service to start
      win_shell: |
        Start-Sleep -Seconds 3
      when: sysmon_exe_file.stat.exists and sysmon_config_file.stat.exists
      ignore_errors: yes

    - name: Verify Sysmon service exists and is running
      win_shell: |
        $sysmon = Get-Service -Name Sysmon64 -ErrorAction SilentlyContinue
        if ($sysmon) {
          Write-Output "✓ Sysmon64 service found"
          Write-Output "  Status: $($sysmon.Status)"
          Write-Output "  Start Type: $($sysmon.StartType)"
          
          # Check event log to verify it's actually logging
          $eventCount = (Get-WinEvent -LogName 'Microsoft-Windows-Sysmon/Operational' -MaxEvents 10 -ErrorAction SilentlyContinue).Count
          if ($eventCount -gt 0) {
            Write-Output "  Events logged: $eventCount (Sysmon is working!)"
          } else {
            Write-Output "  WARNING: No events found yet (may need time to start logging)"
          }
        } else {
          Write-Output "✗ ERROR: Sysmon64 service not found!"
          Write-Output "  This means installation failed"
        }
      register: sysmon_verify
      ignore_errors: yes

    - name: Display Sysmon status
      debug:
        msg: "{{ sysmon_verify.stdout_lines }}"

    # Task 4: Disable WinRM (will be re-enabled temporarily by Ansible as needed)
    - name: Disable WinRM service
      win_service:
        name: WinRM
        start_mode: disabled
        state: stopped
      ignore_errors: yes

    # Task 5: Output registry Run keys
    - name: Check HKCU Run registry keys
      win_shell: |
        Write-Output "`n=== HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Run ==="
        Get-ItemProperty -Path "HKCU:\Software\Microsoft\Windows\CurrentVersion\Run" -ErrorAction SilentlyContinue | Format-List
      register: hkcu_run
      ignore_errors: yes

    - name: Check HKCU RunOnce registry keys
      win_shell: |
        Write-Output "`n=== HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\RunOnce ==="
        Get-ItemProperty -Path "HKCU:\Software\Microsoft\Windows\CurrentVersion\RunOnce" -ErrorAction SilentlyContinue | Format-List
      register: hkcu_runonce
      ignore_errors: yes

    - name: Check HKCU RunServices registry keys
      win_shell: |
        Write-Output "`n=== HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\RunServices ==="
        Get-ItemProperty -Path "HKCU:\Software\Microsoft\Windows\CurrentVersion\RunServices" -ErrorAction SilentlyContinue | Format-List
      register: hkcu_runservices
      ignore_errors: yes

    - name: Check HKCU RunServicesOnce registry keys
      win_shell: |
        Write-Output "`n=== HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\RunServicesOnce ==="
        Get-ItemProperty -Path "HKCU:\Software\Microsoft\Windows\CurrentVersion\RunServicesOnce" -ErrorAction SilentlyContinue | Format-List
      register: hkcu_runservicesonce
      ignore_errors: yes

    - name: Check HKLM Run registry keys
      win_shell: |
        Write-Output "`n=== HKEY_LOCAL_MACHINE\Software\Microsoft\Windows\CurrentVersion\Run ==="
        Get-ItemProperty -Path "HKLM:\Software\Microsoft\Windows\CurrentVersion\Run" -ErrorAction SilentlyContinue | Format-List
      register: hklm_run
      ignore_errors: yes

    - name: Check HKLM RunOnce registry keys
      win_shell: |
        Write-Output "`n=== HKEY_LOCAL_MACHINE\Software\Microsoft\Windows\CurrentVersion\RunOnce ==="
        Get-ItemProperty -Path "HKLM:\Software\Microsoft\Windows\CurrentVersion\RunOnce" -ErrorAction SilentlyContinue | Format-List
      register: hklm_runonce
      ignore_errors: yes

    - name: Display all registry keys
      debug:
        msg: 
          - "{{ hkcu_run.stdout }}"
          - "{{ hkcu_runonce.stdout }}"
          - "{{ hkcu_runservices.stdout }}"
          - "{{ hkcu_runservicesonce.stdout }}"
          - "{{ hklm_run.stdout }}"
          - "{{ hklm_runonce.stdout }}"

    # Task 6: Audit scheduled tasks
    - name: List all scheduled tasks
      win_shell: |
        Write-Output "`n=== SCHEDULED TASKS AUDIT ==="
        Get-ScheduledTask | Where-Object {$_.State -ne 'Disabled'} | 
        Select-Object TaskName, TaskPath, State, @{Name='Author';Expression={$_.Principal.UserId}} |
        Format-Table -AutoSize
      register: scheduled_tasks
      ignore_errors: yes

    - name: Display scheduled tasks
      debug:
        msg: "{{ scheduled_tasks.stdout_lines }}"

    # Task 7: Check startup folders
    - name: Check system startup folder
      win_shell: |
        Write-Output "`n=== SYSTEM STARTUP FOLDER ==="
        $systemStartup = "C:\ProgramData\Microsoft\Windows\Start Menu\Programs\StartUp"
        Get-ChildItem -Path $systemStartup -ErrorAction SilentlyContinue | Format-Table Name, LastWriteTime, Length
      register: system_startup
      ignore_errors: yes

    - name: Check user startup folders
      win_shell: |
        Write-Output "`n=== USER STARTUP FOLDERS ==="
        $users = Get-ChildItem "C:\Users" -Directory
        foreach ($user in $users) {
          $userStartup = Join-Path $user.FullName "AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup"
          if (Test-Path $userStartup) {
            Write-Output "`nStartup folder for $($user.Name):"
            Get-ChildItem -Path $userStartup -ErrorAction SilentlyContinue | Format-Table Name, LastWriteTime, Length
          }
        }
      register: user_startup
      ignore_errors: yes

    - name: Display startup folder contents
      debug:
        msg:
          - "{{ system_startup.stdout_lines }}"
          - "{{ user_startup.stdout_lines }}"

    # Task 8: Audit SMB shares
    - name: List all SMB shares
      win_shell: |
        Write-Output "`n=== SMB SHARES AUDIT ==="
        Get-SmbShare | Format-Table Name, Path, Description, CurrentUsers -AutoSize
        
        Write-Output "`n=== SMB SHARE PERMISSIONS ==="
        $shares = Get-SmbShare | Where-Object {$_.Name -notlike '*$'}
        foreach ($share in $shares) {
          Write-Output "`nShare: $($share.Name)"
          Get-SmbShareAccess -Name $share.Name | Format-Table AccountName, AccessControlType, AccessRight
        }
      register: smb_shares
      ignore_errors: yes

    - name: Display SMB shares
      debug:
        msg: "{{ smb_shares.stdout_lines }}"

    # Task 9: Disable Guest account
    - name: Disable Guest account
      win_user:
        name: Guest
        account_disabled: yes
      ignore_errors: yes

    - name: Verify Guest account is disabled
      win_shell: |
        Get-LocalUser -Name "Guest" | Select-Object Name, Enabled
      register: guest_status
      ignore_errors: yes

    - name: Display Guest account status
      debug:
        msg: "{{ guest_status.stdout }}"

    # Final summary
    - name: Create hardening report
      win_shell: |
        $report = @"
        
        =====================================
        CCDC WINDOWS HARDENING COMPLETE
        =====================================
        Timestamp: $(Get-Date)
        
        Actions Completed:
        [X] SSH service removed
        [X] RDP access restricted to blueteam, greyteam, greyteam2
        [X] Sysinternals tools downloaded to C:\Sysinternals
        [X] WinRM disabled
        [X] Registry Run keys audited
        [X] Scheduled tasks audited
        [X] Startup folders checked
        [X] SMB shares audited
        [X] Guest account disabled
        
        Important Notes:
        - Review the output above for suspicious entries
        - Sysinternals tools are in C:\Sysinternals
        - WinRM has been disabled for security
        - All greyteam users retain admin access
        - No antivirus/firewall rules modified per competition rules
        
        =====================================
        "@
        Write-Output $report
      register: final_report

    - name: Display final report
      debug:
        msg: "{{ final_report.stdout_lines }}"